# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4d3e1281f6d593533a0158a4f2d360758cd36e0ff512cbca101e750cdcf571de9a611d52515305cf989f2863eadcde336ca9621d2af32fc75864cacbcd10129

test:
  secret_key_base: 3932103b990d1c1d83caace5406e4a495e51456a322deb76b0dbf4d2bc59237b36c19d05e9649673819e34302c9c2d5a1176c8d14259bbfc5e4d3529a44249bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
